services:
  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - api1
      - api2
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  api1: &api
    image: thomazmbonfim/rinha-de-backend-2025-2:latest
    hostname: api1
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"
  api2: 
    <<: *api
    hostname: api2
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080

networks:
    backend:
      driver: bridge
    payment-processor: 
      name: payment-processor
      external: true
